spring:
  application:
    name: eureka-client
server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.0.15:8761/eureka}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 35