server:
  port: 8093

spring:
  application:
    name: store-book-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
    stream:
      kafka:
        binder:
          auto-add-partitions: true

      bindings:
        bookEventProcessor-in-0:
          destination: store-book
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

