server:
  port: 8883

spring:
  application:
    name: client-service
  sleuth:
    sampler:
      probability: 2.0
  zipkin:
    enabled: true




feign:
  circuitbreaker:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}



