server:
  port: 8882

spring:
  application:
    name: book-service
  profiles:
    active: dev
  config:
    import: "configserver:"
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
